# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36a3e8499eced92f0117ec786f903b751a16d2dfc299d819ec72bed3e59b54b94d4b13d63784ea792171e17083d05fc1b574f1f0ac153c6fcd56889ab0caa80a

test:
  secret_key_base: 6181893eb95a0c3fbbea413f7421ef7f4a163b88f2dbc6a0854214a98b6337feab7774ede2d2dd0fe19e7b4a34d252ec734c31ccc77ab18d16b0e0b5f220ebab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
